maximum_availability_zones: 5

# Set `ip_blocks` here or export from vpc component
ip_blocks:
  local:
    - 127.0.0.1/32

# CLI to query engine and family: aws rds describe-db-engine-versions, Select appropriate family and engine version

# engineVersion: '9.x.x' | '10.x' | '11.x'
# family: postgres9 | postgres10 | postgres11

publicly_accessible: false
deletion_policy: Snapshot

parameters:
  authentication_timeout: '60'

master_login:
  username_ssm_param: /rds/POSTGRES_MASTER_USERNAME
  password_ssm_param: /rds/POSTGRES_MASTER_PASSWORD

security_group:
  -
    rules:
      -
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
    ips:
      - stack

storage_encrypted: false
#kms_key_id: arn:aws:kms:ap-southeast-2:111111111111:key/12345678-1234-1234-1234-111111111111

